version:     "0001--12-Feb-2022"
copyright:   "2022"
author:      "Linus A. W."
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/linusabhyasaui/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]

theme: jekyll-theme-minimal